/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.parser;

import minipython.lexer.*;
import minipython.node.*;
import minipython.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList nodeList;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_shift;
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(Lexer lexer)
    {
        this.lexer = lexer;

        if(actionTable == null)
        {
            try
            {
                DataInputStream s = new DataInputStream(
                    new BufferedInputStream(
                    Parser.class.getResourceAsStream("parser.dat")));

                // read actionTable
                int length = s.readInt();
                actionTable = new int[length][][];
                for(int i = 0; i < actionTable.length; i++)
                {
                    length = s.readInt();
                    actionTable[i] = new int[length][3];
                    for(int j = 0; j < actionTable[i].length; j++)
                    {
                        for(int k = 0; k < 3; k++)
                        {
                            actionTable[i][j][k] = s.readInt();
                        }
                    }
                }

                // read gotoTable
                length = s.readInt();
                gotoTable = new int[length][][];
                for(int i = 0; i < gotoTable.length; i++)
                {
                    length = s.readInt();
                    gotoTable[i] = new int[length][2];
                    for(int j = 0; j < gotoTable[i].length; j++)
                    {
                        for(int k = 0; k < 2; k++)
                        {
                            gotoTable[i][j][k] = s.readInt();
                        }
                    }
                }

                // read errorMessages
                length = s.readInt();
                errorMessages = new String[length];
                for(int i = 0; i < errorMessages.length; i++)
                {
                    length = s.readInt();
                    StringBuffer buffer = new StringBuffer();

                    for(int j = 0; j < length; j++)
                    {
                        buffer.append(s.readChar());
                    }
                    errorMessages[i] = buffer.toString();
                }

                // read errors
                length = s.readInt();
                errors = new int[length];
                for(int i = 0; i < errors.length; i++)
                {
                    errors[i] = s.readInt();
                }

                s.close();
            }
            catch(Exception e)
            {
                throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
            }
        }
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private void push(int numstate, ArrayList listNode) throws ParserException, LexerException, IOException
    {
	this.nodeList = listNode;

        if(!stack.hasNext())
        {
            stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int state()
    {
        State s = (State) stack.previous();
        stack.next();
        return s.state;
    }

    private ArrayList pop()
    {
        return (ArrayList) ((State) stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        converter.index = -1;
        token.apply(converter);
        return converter.index;
    }

    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null);

        List ign = null;
        while(true)
        {
            while(index(lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new TypedLinkedList(NodeCast.instance);
                }

                ign.add(lexer.next());
            }

            if(ign != null)
            {
                ignoredTokens.setIn(lexer.peek(), ign);
                ign = null;
            }

            last_pos = lexer.peek().getPos();
            last_line = lexer.peek().getLine();
            last_token = lexer.peek();

            int index = index(lexer.peek());
            action[0] = actionTable[state()][0][1];
            action[1] = actionTable[state()][0][2];

            int low = 1;
            int high = actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    action[0] = actionTable[state()][middle][1];
                    action[1] = actionTable[state()][middle][2];
                    break;
                }
            }

            switch(action[0])
            {
                case SHIFT:
		    {
		        ArrayList list = new ArrayList();
		        list.add(lexer.next());
                        push(action[1], list);
                        last_shift = action[1];
                    }
		    break;
                case REDUCE:
                    switch(action[1])
                    {

                    case 0:
		    {
			ArrayList list = new0();
			push(goTo(0), list);
		    }
		    break;


                    case 1:
		    {
			ArrayList list = new1();
			push(goTo(0), list);
		    }
		    break;


                    case 2:
		    {
			ArrayList list = new2();
			push(goTo(1), list);
		    }
		    break;


                    case 3:
		    {
			ArrayList list = new3();
			push(goTo(1), list);
		    }
		    break;


                    case 4:
		    {
			ArrayList list = new4();
			push(goTo(2), list);
		    }
		    break;


                    case 5:
		    {
			ArrayList list = new5();
			push(goTo(2), list);
		    }
		    break;


                    case 6:
		    {
			ArrayList list = new6();
			push(goTo(3), list);
		    }
		    break;


                    case 7:
		    {
			ArrayList list = new7();
			push(goTo(3), list);
		    }
		    break;


                    case 8:
		    {
			ArrayList list = new8();
			push(goTo(3), list);
		    }
		    break;


                    case 9:
		    {
			ArrayList list = new9();
			push(goTo(3), list);
		    }
		    break;


                    case 10:
		    {
			ArrayList list = new10();
			push(goTo(4), list);
		    }
		    break;


                    case 11:
		    {
			ArrayList list = new11();
			push(goTo(5), list);
		    }
		    break;


                    case 12:
		    {
			ArrayList list = new12();
			push(goTo(5), list);
		    }
		    break;


                    case 13:
		    {
			ArrayList list = new13();
			push(goTo(6), list);
		    }
		    break;


                    case 14:
		    {
			ArrayList list = new14();
			push(goTo(6), list);
		    }
		    break;


                    case 15:
		    {
			ArrayList list = new15();
			push(goTo(6), list);
		    }
		    break;


                    case 16:
		    {
			ArrayList list = new16();
			push(goTo(6), list);
		    }
		    break;


                    case 17:
		    {
			ArrayList list = new17();
			push(goTo(6), list);
		    }
		    break;


                    case 18:
		    {
			ArrayList list = new18();
			push(goTo(6), list);
		    }
		    break;


                    case 19:
		    {
			ArrayList list = new19();
			push(goTo(6), list);
		    }
		    break;


                    case 20:
		    {
			ArrayList list = new20();
			push(goTo(6), list);
		    }
		    break;


                    case 21:
		    {
			ArrayList list = new21();
			push(goTo(6), list);
		    }
		    break;


                    case 22:
		    {
			ArrayList list = new22();
			push(goTo(6), list);
		    }
		    break;


                    case 23:
		    {
			ArrayList list = new23();
			push(goTo(6), list);
		    }
		    break;


                    case 24:
		    {
			ArrayList list = new24();
			push(goTo(6), list);
		    }
		    break;


                    case 25:
		    {
			ArrayList list = new25();
			push(goTo(6), list);
		    }
		    break;


                    case 26:
		    {
			ArrayList list = new26();
			push(goTo(6), list);
		    }
		    break;


                    case 27:
		    {
			ArrayList list = new27();
			push(goTo(6), list);
		    }
		    break;


                    case 28:
		    {
			ArrayList list = new28();
			push(goTo(6), list);
		    }
		    break;


                    case 29:
		    {
			ArrayList list = new29();
			push(goTo(7), list);
		    }
		    break;


                    case 30:
		    {
			ArrayList list = new30();
			push(goTo(8), list);
		    }
		    break;


                    case 31:
		    {
			ArrayList list = new31();
			push(goTo(8), list);
		    }
		    break;


                    case 32:
		    {
			ArrayList list = new32();
			push(goTo(8), list);
		    }
		    break;


                    case 33:
		    {
			ArrayList list = new33();
			push(goTo(8), list);
		    }
		    break;


                    case 34:
		    {
			ArrayList list = new34();
			push(goTo(9), list);
		    }
		    break;


                    case 35:
		    {
			ArrayList list = new35();
			push(goTo(10), list);
		    }
		    break;


                    case 36:
		    {
			ArrayList list = new36();
			push(goTo(10), list);
		    }
		    break;


                    case 37:
		    {
			ArrayList list = new37();
			push(goTo(10), list);
		    }
		    break;


                    case 38:
		    {
			ArrayList list = new38();
			push(goTo(11), list);
		    }
		    break;


                    case 39:
		    {
			ArrayList list = new39();
			push(goTo(11), list);
		    }
		    break;


                    case 40:
		    {
			ArrayList list = new40();
			push(goTo(12), list);
		    }
		    break;


                    case 41:
		    {
			ArrayList list = new41();
			push(goTo(12), list);
		    }
		    break;


                    case 42:
		    {
			ArrayList list = new42();
			push(goTo(12), list);
		    }
		    break;


                    case 43:
		    {
			ArrayList list = new43();
			push(goTo(12), list);
		    }
		    break;


                    case 44:
		    {
			ArrayList list = new44();
			push(goTo(13), list);
		    }
		    break;


                    case 45:
		    {
			ArrayList list = new45();
			push(goTo(13), list);
		    }
		    break;


                    case 46:
		    {
			ArrayList list = new46();
			push(goTo(13), list);
		    }
		    break;


                    case 47:
		    {
			ArrayList list = new47();
			push(goTo(14), list);
		    }
		    break;


                    case 48:
		    {
			ArrayList list = new48();
			push(goTo(14), list);
		    }
		    break;


                    case 49:
		    {
			ArrayList list = new49();
			push(goTo(14), list);
		    }
		    break;


                    case 50:
		    {
			ArrayList list = new50();
			push(goTo(14), list);
		    }
		    break;


                    case 51:
		    {
			ArrayList list = new51();
			push(goTo(14), list);
		    }
		    break;


                    case 52:
		    {
			ArrayList list = new52();
			push(goTo(15), list);
		    }
		    break;


                    case 53:
		    {
			ArrayList list = new53();
			push(goTo(15), list);
		    }
		    break;


                    case 54:
		    {
			ArrayList list = new54();
			push(goTo(16), list);
		    }
		    break;


                    case 55:
		    {
			ArrayList list = new55();
			push(goTo(16), list);
		    }
		    break;


                    case 56:
		    {
			ArrayList list = new56();
			push(goTo(17), list);
		    }
		    break;


                    case 57:
		    {
			ArrayList list = new57();
			push(goTo(18), list);
		    }
		    break;


                    case 58:
		    {
			ArrayList list = new58();
			push(goTo(18), list);
		    }
		    break;


                    case 59:
		    {
			ArrayList list = new59();
			push(goTo(19), list);
		    }
		    break;


                    case 60:
		    {
			ArrayList list = new60();
			push(goTo(20), list);
		    }
		    break;


                    case 61:
		    {
			ArrayList list = new61();
			push(goTo(21), list);
		    }
		    break;


                    case 62:
		    {
			ArrayList list = new62();
			push(goTo(21), list);
		    }
		    break;


                    case 63:
		    {
			ArrayList list = new63();
			push(goTo(22), list);
		    }
		    break;


                    case 64:
		    {
			ArrayList list = new64();
			push(goTo(22), list);
		    }
		    break;


                    case 65:
		    {
			ArrayList list = new65();
			push(goTo(23), list);
		    }
		    break;


                    case 66:
		    {
			ArrayList list = new66();
			push(goTo(23), list);
		    }
		    break;


                    case 67:
		    {
			ArrayList list = new67();
			push(goTo(24), list);
		    }
		    break;


                    case 68:
		    {
			ArrayList list = new68();
			push(goTo(24), list);
		    }
		    break;


                    case 69:
		    {
			ArrayList list = new69();
			push(goTo(25), list);
		    }
		    break;


                    case 70:
		    {
			ArrayList list = new70();
			push(goTo(25), list);
		    }
		    break;


                    case 71:
		    {
			ArrayList list = new71();
			push(goTo(26), list);
		    }
		    break;


                    case 72:
		    {
			ArrayList list = new72();
			push(goTo(26), list);
		    }
		    break;

                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) lexer.next();
                        PGoal node1 = (PGoal) ((ArrayList)pop()).get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(last_token,
                        "[" + last_line + "," + last_pos + "] " +
                        errorMessages[errors[action[1]]]);
            }
        }
    }



    ArrayList new0()
    {
        ArrayList nodeList = new ArrayList();

        PGoal pgoalNode1;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        }

        pgoalNode1 = new ACmdsGoal(listNode2);
        }
	nodeList.add(pgoalNode1);
        return nodeList;
    }



    ArrayList new1()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PGoal pgoalNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pgoalNode1 = new ACmdsGoal(listNode3);
        }
	nodeList.add(pgoalNode1);
        return nodeList;
    }



    ArrayList new2()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCommands pcommandsNode1;
        {
        PFunction pfunctionNode2;
        pfunctionNode2 = (PFunction)nodeArrayList1.get(0);

        pcommandsNode1 = new AFuncCommands(pfunctionNode2);
        }
	nodeList.add(pcommandsNode1);
        return nodeList;
    }



    ArrayList new3()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCommands pcommandsNode1;
        {
        PStatement pstatementNode2;
        pstatementNode2 = (PStatement)nodeArrayList1.get(0);

        pcommandsNode1 = new AStmtCommands(pstatementNode2);
        }
	nodeList.add(pcommandsNode1);
        return nodeList;
    }



    ArrayList new4()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunction pfunctionNode1;
        {
        PIdentifier pidentifierNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        PStatement pstatementNode4;
        pidentifierNode2 = (PIdentifier)nodeArrayList2.get(0);
        {
        }
        pstatementNode4 = (PStatement)nodeArrayList6.get(0);

        pfunctionNode1 = new AFuncFunction(pidentifierNode2, listNode3, pstatementNode4);
        }
	nodeList.add(pfunctionNode1);
        return nodeList;
    }



    ArrayList new5()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunction pfunctionNode1;
        {
        PIdentifier pidentifierNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        PStatement pstatementNode5;
        pidentifierNode2 = (PIdentifier)nodeArrayList2.get(0);
        {
        PArgument pargumentNode3;
        pargumentNode3 = (PArgument)nodeArrayList4.get(0);
	if(pargumentNode3 != null)
	{
	  listNode4.add(pargumentNode3);
	}
        }
        pstatementNode5 = (PStatement)nodeArrayList7.get(0);

        pfunctionNode1 = new AFuncFunction(pidentifierNode2, listNode4, pstatementNode5);
        }
	nodeList.add(pfunctionNode1);
        return nodeList;
    }



    ArrayList new6()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        PIdentifier pidentifierNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        TypedLinkedList listNode4 = new TypedLinkedList();
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);
        {
        }
        {
        }

        pargumentNode1 = new AArgArgument(pidentifierNode2, listNode3, listNode4);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new7()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        PIdentifier pidentifierNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        TypedLinkedList listNode5 = new TypedLinkedList();
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);
        {
        PAssignValue passignvalueNode3;
        passignvalueNode3 = (PAssignValue)nodeArrayList2.get(0);
	if(passignvalueNode3 != null)
	{
	  listNode4.add(passignvalueNode3);
	}
        }
        {
        }

        pargumentNode1 = new AArgArgument(pidentifierNode2, listNode4, listNode5);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new8()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        PIdentifier pidentifierNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        TypedLinkedList listNode5 = new TypedLinkedList();
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);
        {
        }
        {
        TypedLinkedList listNode4 = new TypedLinkedList();
        listNode4 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pargumentNode1 = new AArgArgument(pidentifierNode2, listNode3, listNode5);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new9()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        PIdentifier pidentifierNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        TypedLinkedList listNode6 = new TypedLinkedList();
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);
        {
        PAssignValue passignvalueNode3;
        passignvalueNode3 = (PAssignValue)nodeArrayList2.get(0);
	if(passignvalueNode3 != null)
	{
	  listNode4.add(passignvalueNode3);
	}
        }
        {
        TypedLinkedList listNode5 = new TypedLinkedList();
        listNode5 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode5 != null)
	{
	  listNode6.addAll(listNode5);
	}
        }

        pargumentNode1 = new AArgArgument(pidentifierNode2, listNode4, listNode6);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new10()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PAssignValue passignvalueNode1;
        {
        PValue pvalueNode2;
        pvalueNode2 = (PValue)nodeArrayList2.get(0);

        passignvalueNode1 = new AAssignValue(pvalueNode2);
        }
	nodeList.add(passignvalueNode1);
        return nodeList;
    }



    ArrayList new11()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMoreArguments pmoreargumentsNode1;
        {
        PIdentifier pidentifierNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pidentifierNode2 = (PIdentifier)nodeArrayList2.get(0);
        {
        }

        pmoreargumentsNode1 = new AMoreArguments(pidentifierNode2, listNode3);
        }
	nodeList.add(pmoreargumentsNode1);
        return nodeList;
    }



    ArrayList new12()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMoreArguments pmoreargumentsNode1;
        {
        PIdentifier pidentifierNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pidentifierNode2 = (PIdentifier)nodeArrayList2.get(0);
        {
        PAssignValue passignvalueNode3;
        passignvalueNode3 = (PAssignValue)nodeArrayList3.get(0);
	if(passignvalueNode3 != null)
	{
	  listNode4.add(passignvalueNode3);
	}
        }

        pmoreargumentsNode1 = new AMoreArguments(pidentifierNode2, listNode4);
        }
	nodeList.add(pmoreargumentsNode1);
        return nodeList;
    }



    ArrayList new13()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList2.get(0);
        pstatementNode3 = (PStatement)nodeArrayList4.get(0);

        pstatementNode1 = new ARule1Statement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new14()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList3.get(0);
        pstatementNode3 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new ARule1Statement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new15()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PIdentifier pidentifierNode2;
        PIdentifier pidentifierNode3;
        PStatement pstatementNode4;
        pidentifierNode2 = (PIdentifier)nodeArrayList2.get(0);
        pidentifierNode3 = (PIdentifier)nodeArrayList4.get(0);
        pstatementNode4 = (PStatement)nodeArrayList6.get(0);

        pstatementNode1 = new ARule2Statement(pidentifierNode2, pidentifierNode3, pstatementNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new16()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PIdentifier pidentifierNode2;
        PIdentifier pidentifierNode3;
        PStatement pstatementNode4;
        pidentifierNode2 = (PIdentifier)nodeArrayList3.get(0);
        pidentifierNode3 = (PIdentifier)nodeArrayList5.get(0);
        pstatementNode4 = (PStatement)nodeArrayList7.get(0);

        pstatementNode1 = new ARule2Statement(pidentifierNode2, pidentifierNode3, pstatementNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new17()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        pstatementNode1 = new ARule7Statement(pexpressionNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new18()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new ARule7Statement(pexpressionNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new19()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        }

        pstatementNode1 = new ARule3Statement(pexpressionNode2, listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new20()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        {
        }

        pstatementNode1 = new ARule3Statement(pexpressionNode2, listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new21()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pstatementNode1 = new ARule3Statement(pexpressionNode2, listNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new22()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pstatementNode1 = new ARule3Statement(pexpressionNode2, listNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new23()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PIdentifier pidentifierNode2;
        PExpression pexpressionNode3;
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new ARule4Statement(pidentifierNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new24()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PIdentifier pidentifierNode2;
        PExpression pexpressionNode3;
        pidentifierNode2 = (PIdentifier)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);

        pstatementNode1 = new ARule4Statement(pidentifierNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new25()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PIdentifier pidentifierNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode4;
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList6.get(0);

        pstatementNode1 = new ARule5Statement(pidentifierNode2, pexpressionNode3, pexpressionNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new26()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PIdentifier pidentifierNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode4;
        pidentifierNode2 = (PIdentifier)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList7.get(0);

        pstatementNode1 = new ARule5Statement(pidentifierNode2, pexpressionNode3, pexpressionNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new27()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PFunctionCall pfunctioncallNode2;
        pfunctioncallNode2 = (PFunctionCall)nodeArrayList1.get(0);

        pstatementNode1 = new ARule6Statement(pfunctioncallNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new28()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PFunctionCall pfunctioncallNode2;
        pfunctioncallNode2 = (PFunctionCall)nodeArrayList2.get(0);

        pstatementNode1 = new ARule6Statement(pfunctioncallNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new29()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMoreExpressions pmoreexpressionsNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        pmoreexpressionsNode1 = new AMoreExpressions(pexpressionNode2);
        }
	nodeList.add(pmoreexpressionsNode1);
        return nodeList;
    }



    ArrayList new30()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new31()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PIdentifier pidentifierNode2;
        PExpression pexpressionNode3;
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new ARule2Expression(pidentifierNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new32()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PValue pvalueNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pvalueNode2 = (PValue)nodeArrayList2.get(0);
        {
        }

        pexpressionNode1 = new ARule3Expression(pvalueNode2, listNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new33()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PValue pvalueNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pvalueNode2 = (PValue)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pexpressionNode1 = new ARule3Expression(pvalueNode2, listNode4);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new34()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMoreValues pmorevaluesNode1;
        {
        PValue pvalueNode2;
        pvalueNode2 = (PValue)nodeArrayList2.get(0);

        pmorevaluesNode1 = new AMoreValues(pvalueNode2);
        }
	nodeList.add(pmorevaluesNode1);
        return nodeList;
    }



    ArrayList new35()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new36()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AAddExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new37()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AMinusExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new38()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new39()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AMultExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new40()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PValue pvalueNode2;
        pvalueNode2 = (PValue)nodeArrayList1.get(0);

        pexpressionNode1 = new AValueExpression(pvalueNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new41()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PIdentifier pidentifierNode2;
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);

        pexpressionNode1 = new AIdExpression(pidentifierNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new42()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PFunctionCall pfunctioncallNode2;
        pfunctioncallNode2 = (PFunctionCall)nodeArrayList1.get(0);

        pexpressionNode1 = new AFuncExpression(pfunctioncallNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new43()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        pexpressionNode1 = new AExpExpression(pexpressionNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new44()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new ARule1Comparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new45()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        Object nullNode1 = null;
	nodeList.add(nullNode1);
        return nodeList;
    }



    ArrayList new46()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        Object nullNode1 = null;
	nodeList.add(nullNode1);
        return nodeList;
    }



    ArrayList new47()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        return nodeList;
    }



    ArrayList new48()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        return nodeList;
    }



    ArrayList new49()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        return nodeList;
    }



    ArrayList new50()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        return nodeList;
    }



    ArrayList new51()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        return nodeList;
    }



    ArrayList new52()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunctionCall pfunctioncallNode1;
        {
        PIdentifier pidentifierNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);
        {
        }

        pfunctioncallNode1 = new AFunctionCall(pidentifierNode2, listNode3);
        }
	nodeList.add(pfunctioncallNode1);
        return nodeList;
    }



    ArrayList new53()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunctionCall pfunctioncallNode1;
        {
        PIdentifier pidentifierNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pidentifierNode2 = (PIdentifier)nodeArrayList1.get(0);
        {
        PArgList parglistNode3;
        parglistNode3 = (PArgList)nodeArrayList3.get(0);
	if(parglistNode3 != null)
	{
	  listNode4.add(parglistNode3);
	}
        }

        pfunctioncallNode1 = new AFunctionCall(pidentifierNode2, listNode4);
        }
	nodeList.add(pfunctioncallNode1);
        return nodeList;
    }



    ArrayList new54()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgList parglistNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        }

        parglistNode1 = new AArgList(pexpressionNode2, listNode3);
        }
	nodeList.add(parglistNode1);
        return nodeList;
    }



    ArrayList new55()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgList parglistNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        parglistNode1 = new AArgList(pexpressionNode2, listNode4);
        }
	nodeList.add(parglistNode1);
        return nodeList;
    }



    ArrayList new56()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMoreListArguments pmorelistargumentsNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        pmorelistargumentsNode1 = new AMoreListArguments(pexpressionNode2);
        }
	nodeList.add(pmorelistargumentsNode1);
        return nodeList;
    }



    ArrayList new57()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        PNumber pnumberNode2;
        pnumberNode2 = (PNumber)nodeArrayList1.get(0);

        pvalueNode1 = new ANumberValue(pnumberNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new58()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TString tstringNode2;
        tstringNode2 = (TString)nodeArrayList1.get(0);

        pvalueNode1 = new AStringValue(tstringNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new59()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PNumber pnumberNode1;
        {
        TInteger tintegerNode2;
        tintegerNode2 = (TInteger)nodeArrayList1.get(0);

        pnumberNode1 = new AIntNumber(tintegerNode2);
        }
	nodeList.add(pnumberNode1);
        return nodeList;
    }



    ArrayList new60()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PIdentifier pidentifierNode1;
        {
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList1.get(0);

        pidentifierNode1 = new AIdentifier(tidNode2);
        }
	nodeList.add(pidentifierNode1);
        return nodeList;
    }



    ArrayList new61()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PCommands pcommandsNode1;
        pcommandsNode1 = (PCommands)nodeArrayList1.get(0);
	if(pcommandsNode1 != null)
	{
	  listNode2.add(pcommandsNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new62()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PCommands pcommandsNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pcommandsNode2 = (PCommands)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pcommandsNode2 != null)
	{
	  listNode3.add(pcommandsNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new63()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PMoreArguments pmoreargumentsNode1;
        pmoreargumentsNode1 = (PMoreArguments)nodeArrayList1.get(0);
	if(pmoreargumentsNode1 != null)
	{
	  listNode2.add(pmoreargumentsNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new64()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PMoreArguments pmoreargumentsNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pmoreargumentsNode2 = (PMoreArguments)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pmoreargumentsNode2 != null)
	{
	  listNode3.add(pmoreargumentsNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new65()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        TTab ttabNode1;
        ttabNode1 = (TTab)nodeArrayList1.get(0);
	if(ttabNode1 != null)
	{
	  listNode2.add(ttabNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new66()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        TTab ttabNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        ttabNode2 = (TTab)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(ttabNode2 != null)
	{
	  listNode3.add(ttabNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new67()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PMoreExpressions pmoreexpressionsNode1;
        pmoreexpressionsNode1 = (PMoreExpressions)nodeArrayList1.get(0);
	if(pmoreexpressionsNode1 != null)
	{
	  listNode2.add(pmoreexpressionsNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new68()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PMoreExpressions pmoreexpressionsNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pmoreexpressionsNode2 = (PMoreExpressions)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pmoreexpressionsNode2 != null)
	{
	  listNode3.add(pmoreexpressionsNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new69()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PMoreValues pmorevaluesNode1;
        pmorevaluesNode1 = (PMoreValues)nodeArrayList1.get(0);
	if(pmorevaluesNode1 != null)
	{
	  listNode2.add(pmorevaluesNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new70()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PMoreValues pmorevaluesNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pmorevaluesNode2 = (PMoreValues)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pmorevaluesNode2 != null)
	{
	  listNode3.add(pmorevaluesNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new71()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PMoreListArguments pmorelistargumentsNode1;
        pmorelistargumentsNode1 = (PMoreListArguments)nodeArrayList1.get(0);
	if(pmorelistargumentsNode1 != null)
	{
	  listNode2.add(pmorelistargumentsNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new72()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PMoreListArguments pmorelistargumentsNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pmorelistargumentsNode2 = (PMoreListArguments)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pmorelistargumentsNode2 != null)
	{
	  listNode3.add(pmorelistargumentsNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, REDUCE, 0}, {0, SHIFT, 1}, {17, SHIFT, 2}, {19, SHIFT, 3}, {20, SHIFT, 4}, {21, SHIFT, 5}, {22, SHIFT, 6}, {27, SHIFT, 7}, },
			{{-1, REDUCE, 65}, },
			{{-1, ERROR, 2}, {11, SHIFT, 16}, {14, SHIFT, 17}, {23, SHIFT, 18}, {24, SHIFT, 19}, {26, SHIFT, 20}, {27, SHIFT, 7}, {28, SHIFT, 21}, },
			{{-1, ERROR, 3}, {27, SHIFT, 7}, },
			{{-1, ERROR, 4}, {11, SHIFT, 16}, {14, SHIFT, 17}, {26, SHIFT, 20}, {27, SHIFT, 7}, {28, SHIFT, 21}, },
			{{-1, ERROR, 5}, {11, SHIFT, 16}, {14, SHIFT, 17}, {26, SHIFT, 20}, {27, SHIFT, 7}, {28, SHIFT, 21}, },
			{{-1, ERROR, 6}, {27, SHIFT, 7}, },
			{{-1, REDUCE, 60}, },
			{{-1, ERROR, 8}, {29, ACCEPT, -1}, },
			{{-1, REDUCE, 61}, },
			{{-1, REDUCE, 2}, },
			{{-1, REDUCE, 3}, },
			{{-1, REDUCE, 27}, },
			{{-1, ERROR, 13}, {5, SHIFT, 35}, {11, SHIFT, 36}, {14, SHIFT, 37}, },
			{{-1, REDUCE, 1}, {0, SHIFT, 1}, {17, SHIFT, 2}, {19, SHIFT, 3}, {20, SHIFT, 4}, {21, SHIFT, 5}, {22, SHIFT, 6}, {27, SHIFT, 7}, },
			{{-1, ERROR, 15}, {0, SHIFT, 39}, {17, SHIFT, 40}, {19, SHIFT, 41}, {20, SHIFT, 42}, {21, SHIFT, 43}, {27, SHIFT, 7}, },
			{{-1, ERROR, 16}, {11, SHIFT, 16}, {14, SHIFT, 17}, {26, SHIFT, 20}, {27, SHIFT, 7}, {28, SHIFT, 21}, },
			{{-1, ERROR, 17}, {26, SHIFT, 20}, {28, SHIFT, 21}, },
			{{-1, REDUCE, 45}, },
			{{-1, REDUCE, 46}, },
			{{-1, REDUCE, 59}, },
			{{-1, REDUCE, 58}, },
			{{-1, ERROR, 22}, {6, SHIFT, 48}, {7, SHIFT, 49}, {8, SHIFT, 50}, {9, SHIFT, 51}, {10, SHIFT, 52}, },
			{{-1, REDUCE, 30}, },
			{{-1, REDUCE, 35}, {2, SHIFT, 54}, {3, SHIFT, 55}, {4, SHIFT, 56}, },
			{{-1, REDUCE, 38}, },
			{{-1, ERROR, 26}, {16, SHIFT, 57}, },
			{{-1, REDUCE, 42}, },
			{{-1, REDUCE, 40}, },
			{{-1, REDUCE, 57}, },
			{{-1, REDUCE, 41}, {11, SHIFT, 36}, {14, SHIFT, 58}, },
			{{-1, ERROR, 31}, {25, SHIFT, 59}, },
			{{-1, REDUCE, 19}, {15, SHIFT, 60}, },
			{{-1, REDUCE, 17}, },
			{{-1, ERROR, 34}, {11, SHIFT, 63}, },
			{{-1, ERROR, 35}, {11, SHIFT, 16}, {14, SHIFT, 17}, {26, SHIFT, 20}, {27, SHIFT, 7}, {28, SHIFT, 21}, },
			{{-1, ERROR, 36}, {11, SHIFT, 16}, {12, SHIFT, 65}, {14, SHIFT, 17}, {26, SHIFT, 20}, {27, SHIFT, 7}, {28, SHIFT, 21}, },
			{{-1, ERROR, 37}, {11, SHIFT, 16}, {14, SHIFT, 17}, {26, SHIFT, 20}, {27, SHIFT, 7}, {28, SHIFT, 21}, },
			{{-1, REDUCE, 62}, },
			{{-1, REDUCE, 66}, },
			{{-1, ERROR, 40}, {11, SHIFT, 16}, {14, SHIFT, 17}, {23, SHIFT, 18}, {24, SHIFT, 19}, {26, SHIFT, 20}, {27, SHIFT, 7}, {28, SHIFT, 21}, },
			{{-1, ERROR, 41}, {27, SHIFT, 7}, },
			{{-1, ERROR, 42}, {11, SHIFT, 16}, {14, SHIFT, 17}, {26, SHIFT, 20}, {27, SHIFT, 7}, {28, SHIFT, 21}, },
			{{-1, ERROR, 43}, {11, SHIFT, 16}, {14, SHIFT, 17}, {26, SHIFT, 20}, {27, SHIFT, 7}, {28, SHIFT, 21}, },
			{{-1, REDUCE, 28}, },
			{{-1, ERROR, 45}, {5, SHIFT, 73}, {11, SHIFT, 36}, {14, SHIFT, 74}, },
			{{-1, ERROR, 46}, {12, SHIFT, 75}, },
			{{-1, ERROR, 47}, {13, SHIFT, 76}, {15, SHIFT, 77}, },
			{{-1, REDUCE, 51}, },
			{{-1, REDUCE, 47}, },
			{{-1, REDUCE, 49}, },
			{{-1, REDUCE, 48}, },
			{{-1, REDUCE, 50}, },
			{{-1, ERROR, 53}, {11, SHIFT, 16}, {14, SHIFT, 17}, {26, SHIFT, 20}, {27, SHIFT, 7}, {28, SHIFT, 21}, },
			{{-1, ERROR, 54}, {11, SHIFT, 16}, {14, SHIFT, 17}, {26, SHIFT, 20}, {27, SHIFT, 7}, {28, SHIFT, 21}, },
			{{-1, ERROR, 55}, {11, SHIFT, 16}, {14, SHIFT, 17}, {26, SHIFT, 20}, {27, SHIFT, 7}, {28, SHIFT, 21}, },
			{{-1, ERROR, 56}, {11, SHIFT, 16}, {26, SHIFT, 20}, {27, SHIFT, 7}, {28, SHIFT, 21}, },
			{{-1, ERROR, 57}, {0, SHIFT, 1}, {17, SHIFT, 2}, {19, SHIFT, 3}, {20, SHIFT, 4}, {21, SHIFT, 5}, {27, SHIFT, 7}, },
			{{-1, ERROR, 58}, {11, SHIFT, 16}, {14, SHIFT, 17}, {26, SHIFT, 20}, {27, SHIFT, 7}, {28, SHIFT, 21}, },
			{{-1, ERROR, 59}, {27, SHIFT, 7}, },
			{{-1, ERROR, 60}, {11, SHIFT, 16}, {14, SHIFT, 17}, {26, SHIFT, 20}, {27, SHIFT, 7}, {28, SHIFT, 21}, },
			{{-1, REDUCE, 67}, },
			{{-1, REDUCE, 21}, {15, SHIFT, 60}, },
			{{-1, ERROR, 63}, {12, SHIFT, 90}, {27, SHIFT, 7}, },
			{{-1, REDUCE, 23}, },
			{{-1, REDUCE, 52}, },
			{{-1, REDUCE, 54}, {15, SHIFT, 93}, },
			{{-1, ERROR, 67}, {12, SHIFT, 96}, },
			{{-1, ERROR, 68}, {13, SHIFT, 97}, },
			{{-1, ERROR, 69}, {16, SHIFT, 98}, },
			{{-1, ERROR, 70}, {25, SHIFT, 99}, },
			{{-1, REDUCE, 20}, {15, SHIFT, 60}, },
			{{-1, REDUCE, 18}, },
			{{-1, ERROR, 73}, {11, SHIFT, 16}, {14, SHIFT, 17}, {26, SHIFT, 20}, {27, SHIFT, 7}, {28, SHIFT, 21}, },
			{{-1, ERROR, 74}, {11, SHIFT, 16}, {14, SHIFT, 17}, {26, SHIFT, 20}, {27, SHIFT, 7}, {28, SHIFT, 21}, },
			{{-1, REDUCE, 43}, },
			{{-1, REDUCE, 32}, },
			{{-1, ERROR, 77}, {26, SHIFT, 20}, {28, SHIFT, 21}, },
			{{-1, REDUCE, 69}, },
			{{-1, ERROR, 79}, {13, SHIFT, 104}, {15, SHIFT, 77}, },
			{{-1, REDUCE, 44}, },
			{{-1, REDUCE, 36}, },
			{{-1, REDUCE, 37}, },
			{{-1, REDUCE, 39}, },
			{{-1, REDUCE, 41}, {11, SHIFT, 36}, },
			{{-1, REDUCE, 13}, },
			{{-1, ERROR, 86}, {13, SHIFT, 106}, },
			{{-1, ERROR, 87}, {16, SHIFT, 107}, },
			{{-1, REDUCE, 29}, },
			{{-1, REDUCE, 68}, },
			{{-1, ERROR, 90}, {16, SHIFT, 108}, },
			{{-1, ERROR, 91}, {12, SHIFT, 109}, },
			{{-1, REDUCE, 6}, {5, SHIFT, 110}, {15, SHIFT, 111}, },
			{{-1, ERROR, 93}, {11, SHIFT, 16}, {14, SHIFT, 17}, {26, SHIFT, 20}, {27, SHIFT, 7}, {28, SHIFT, 21}, },
			{{-1, REDUCE, 71}, },
			{{-1, REDUCE, 55}, {15, SHIFT, 93}, },
			{{-1, REDUCE, 53}, },
			{{-1, ERROR, 97}, {5, SHIFT, 117}, },
			{{-1, ERROR, 98}, {0, SHIFT, 1}, {17, SHIFT, 2}, {19, SHIFT, 3}, {20, SHIFT, 4}, {21, SHIFT, 5}, {27, SHIFT, 7}, },
			{{-1, ERROR, 99}, {27, SHIFT, 7}, },
			{{-1, REDUCE, 22}, {15, SHIFT, 60}, },
			{{-1, REDUCE, 24}, },
			{{-1, ERROR, 102}, {13, SHIFT, 120}, },
			{{-1, REDUCE, 34}, },
			{{-1, REDUCE, 33}, },
			{{-1, REDUCE, 70}, },
			{{-1, REDUCE, 31}, },
			{{-1, ERROR, 107}, {0, SHIFT, 1}, {17, SHIFT, 2}, {19, SHIFT, 3}, {20, SHIFT, 4}, {21, SHIFT, 5}, {27, SHIFT, 7}, },
			{{-1, ERROR, 108}, {0, SHIFT, 1}, {17, SHIFT, 2}, {19, SHIFT, 3}, {20, SHIFT, 4}, {21, SHIFT, 5}, {27, SHIFT, 7}, },
			{{-1, ERROR, 109}, {16, SHIFT, 123}, },
			{{-1, ERROR, 110}, {26, SHIFT, 20}, {28, SHIFT, 21}, },
			{{-1, ERROR, 111}, {27, SHIFT, 7}, },
			{{-1, REDUCE, 7}, {15, SHIFT, 111}, },
			{{-1, REDUCE, 63}, },
			{{-1, REDUCE, 8}, {15, SHIFT, 111}, },
			{{-1, REDUCE, 56}, },
			{{-1, REDUCE, 72}, },
			{{-1, ERROR, 117}, {11, SHIFT, 16}, {14, SHIFT, 17}, {26, SHIFT, 20}, {27, SHIFT, 7}, {28, SHIFT, 21}, },
			{{-1, REDUCE, 14}, },
			{{-1, ERROR, 119}, {16, SHIFT, 129}, },
			{{-1, ERROR, 120}, {5, SHIFT, 130}, },
			{{-1, REDUCE, 15}, },
			{{-1, REDUCE, 4}, },
			{{-1, ERROR, 123}, {0, SHIFT, 1}, {17, SHIFT, 2}, {19, SHIFT, 3}, {20, SHIFT, 4}, {21, SHIFT, 5}, {27, SHIFT, 7}, },
			{{-1, REDUCE, 10}, },
			{{-1, REDUCE, 11}, {5, SHIFT, 110}, },
			{{-1, REDUCE, 9}, {15, SHIFT, 111}, },
			{{-1, REDUCE, 64}, },
			{{-1, REDUCE, 25}, },
			{{-1, ERROR, 129}, {0, SHIFT, 1}, {17, SHIFT, 2}, {19, SHIFT, 3}, {20, SHIFT, 4}, {21, SHIFT, 5}, {27, SHIFT, 7}, },
			{{-1, ERROR, 130}, {11, SHIFT, 16}, {14, SHIFT, 17}, {26, SHIFT, 20}, {27, SHIFT, 7}, {28, SHIFT, 21}, },
			{{-1, REDUCE, 5}, },
			{{-1, REDUCE, 12}, },
			{{-1, REDUCE, 16}, },
			{{-1, REDUCE, 26}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 8}, },
			{{-1, 9}, {14, 38}, },
			{{-1, 10}, },
			{{-1, 91}, },
			{{-1, 112}, {125, 132}, },
			{{-1, 113}, {114, 127}, {126, 127}, },
			{{-1, 11}, {57, 85}, {98, 118}, {107, 121}, {108, 122}, {123, 131}, {129, 133}, },
			{{-1, 61}, {62, 89}, {100, 89}, },
			{{-1, 22}, {4, 32}, {5, 33}, {16, 46}, {35, 64}, {36, 66}, {37, 68}, {42, 71}, {43, 72}, {53, 80}, {54, 81}, {55, 82}, {58, 86}, {60, 88}, {73, 101}, {74, 102}, {93, 115}, {117, 128}, {130, 134}, },
			{{-1, 78}, {79, 105}, },
			{{-1, 23}, },
			{{-1, 24}, },
			{{-1, 25}, {56, 83}, },
			{{-1, 26}, {40, 69}, },
			{{-1, 53}, },
			{{-1, 27}, {0, 12}, {14, 12}, {15, 44}, {57, 12}, {98, 12}, {107, 12}, {108, 12}, {123, 12}, {129, 12}, },
			{{-1, 67}, },
			{{-1, 94}, {95, 116}, },
			{{-1, 28}, {17, 47}, {77, 103}, {110, 124}, },
			{{-1, 29}, },
			{{-1, 30}, {0, 13}, {3, 31}, {6, 34}, {14, 13}, {15, 45}, {41, 70}, {56, 84}, {57, 13}, {59, 87}, {63, 92}, {98, 13}, {99, 119}, {107, 13}, {108, 13}, {111, 125}, {123, 13}, {129, 13}, },
			{{-1, 14}, },
			{{-1, 114}, {112, 126}, },
			{{-1, 15}, },
			{{-1, 62}, {71, 100}, },
			{{-1, 79}, },
			{{-1, 95}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: tab, 'if', 'for', 'print', 'return', 'def', id, EOF",
			"expecting: tab, 'if', 'for', 'print', 'return', id",
			"expecting: '(', '[', 'true', 'false', integer, id, string",
			"expecting: id",
			"expecting: '(', '[', integer, id, string",
			"expecting: tab, '+', '-', '*', '=', '==', '>', '>=', '<', '<=', '(', ')', ']', '[', ',', ':', 'if', 'for', 'print', 'return', 'def', 'in', id, EOF",
			"expecting: EOF",
			"expecting: '=', '(', '['",
			"expecting: integer, string",
			"expecting: ':'",
			"expecting: tab, '+', '-', '*', '==', '>', '>=', '<', '<=', ')', ']', ',', ':', 'if', 'for', 'print', 'return', 'def', id, EOF",
			"expecting: '==', '>', '>=', '<', '<='",
			"expecting: tab, '==', '>', '>=', '<', '<=', ')', ']', ',', ':', 'if', 'for', 'print', 'return', 'def', id, EOF",
			"expecting: tab, '+', '-', '*', '==', '>', '>=', '<', '<=', '(', ')', ']', '[', ',', ':', 'if', 'for', 'print', 'return', 'def', id, EOF",
			"expecting: 'in'",
			"expecting: tab, ',', 'if', 'for', 'print', 'return', 'def', id, EOF",
			"expecting: '('",
			"expecting: '(', ')', '[', integer, id, string",
			"expecting: ')'",
			"expecting: ']', ','",
			"expecting: '(', integer, id, string",
			"expecting: ')', id",
			"expecting: ')', ','",
			"expecting: ']'",
			"expecting: tab, '+', '-', '*', '==', '>', '>=', '<', '<=', '(', ')', ']', ',', ':', 'if', 'for', 'print', 'return', 'def', id, EOF",
			"expecting: '=', ')', ','",
			"expecting: '='",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 4, 4, 3, 5, 6, 0, 0, 0, 0, 7, 0, 1, 4, 8, 9, 9, 10, 10, 11, 12, 10, 10, 9, 10, 10, 10, 13, 14, 15, 0, 16, 4, 17, 4, 0, 1, 2, 3, 4, 4, 0, 7, 18, 19, 4, 4, 4, 4, 4, 4, 4, 4, 20, 1, 4, 3, 4, 15, 15, 21, 0, 10, 22, 18, 23, 9, 14, 15, 0, 4, 4, 10, 12, 8, 19, 19, 9, 12, 12, 10, 24, 0, 23, 9, 15, 15, 9, 18, 25, 4, 22, 22, 10, 26, 1, 3, 15, 0, 23, 19, 12, 19, 12, 1, 1, 9, 8, 3, 22, 22, 22, 22, 22, 4, 0, 9, 26, 0, 0, 1, 22, 25, 22, 22, 0, 1, 4, 0, 22, 0, 0, 
        };*/
}
