/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.parser;

import minipython.node.*;
import minipython.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    public void caseTTab(TTab node)
    {
        index = 0;
    }

    public void caseTExMark(TExMark node)
    {
        index = 1;
    }

    public void caseTPlus(TPlus node)
    {
        index = 2;
    }

    public void caseTMinus(TMinus node)
    {
        index = 3;
    }

    public void caseTMult(TMult node)
    {
        index = 4;
    }

    public void caseTAssign(TAssign node)
    {
        index = 5;
    }

    public void caseTEquals(TEquals node)
    {
        index = 6;
    }

    public void caseTGrt(TGrt node)
    {
        index = 7;
    }

    public void caseTGte(TGte node)
    {
        index = 8;
    }

    public void caseTLt(TLt node)
    {
        index = 9;
    }

    public void caseTLte(TLte node)
    {
        index = 10;
    }

    public void caseTLeftPar(TLeftPar node)
    {
        index = 11;
    }

    public void caseTRightPar(TRightPar node)
    {
        index = 12;
    }

    public void caseTSquareRightBr(TSquareRightBr node)
    {
        index = 13;
    }

    public void caseTSquareLeftBr(TSquareLeftBr node)
    {
        index = 14;
    }

    public void caseTComma(TComma node)
    {
        index = 15;
    }

    public void caseTSemi(TSemi node)
    {
        index = 16;
    }

    public void caseTIf(TIf node)
    {
        index = 17;
    }

    public void caseTWhile(TWhile node)
    {
        index = 18;
    }

    public void caseTFor(TFor node)
    {
        index = 19;
    }

    public void caseTPrint(TPrint node)
    {
        index = 20;
    }

    public void caseTReturn(TReturn node)
    {
        index = 21;
    }

    public void caseTDef(TDef node)
    {
        index = 22;
    }

    public void caseTTrue(TTrue node)
    {
        index = 23;
    }

    public void caseTFalse(TFalse node)
    {
        index = 24;
    }

    public void caseTIn(TIn node)
    {
        index = 25;
    }

    public void caseTInteger(TInteger node)
    {
        index = 26;
    }

    public void caseTId(TId node)
    {
        index = 27;
    }

    public void caseTString(TString node)
    {
        index = 28;
    }

    public void caseEOF(EOF node)
    {
        index = 29;
    }
}
