/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AAddExpression extends PExpression
{
    private PExpression _left_;
    private PExpression _right_;

    public AAddExpression()
    {
    }

    public AAddExpression(
        PExpression _left_,
        PExpression _right_)
    {
        setLeft(_left_);

        setRight(_right_);

    }
    public Object clone()
    {
        return new AAddExpression(
            (PExpression) cloneNode(_left_),
            (PExpression) cloneNode(_right_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAddExpression(this);
    }

    public PExpression getLeft()
    {
        return _left_;
    }

    public void setLeft(PExpression node)
    {
        if(_left_ != null)
        {
            _left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _left_ = node;
    }

    public PExpression getRight()
    {
        return _right_;
    }

    public void setRight(PExpression node)
    {
        if(_right_ != null)
        {
            _right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _right_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_left_)
            + toString(_right_);
    }

    void removeChild(Node child)
    {
        if(_left_ == child)
        {
            _left_ = null;
            return;
        }

        if(_right_ == child)
        {
            _right_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_left_ == oldChild)
        {
            setLeft((PExpression) newChild);
            return;
        }

        if(_right_ == oldChild)
        {
            setRight((PExpression) newChild);
            return;
        }

    }
}
