/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AArgList extends PArgList
{
    private PExpression _expression_;
    private final LinkedList _moreListArguments_ = new TypedLinkedList(new MoreListArguments_Cast());

    public AArgList()
    {
    }

    public AArgList(
        PExpression _expression_,
        List _moreListArguments_)
    {
        setExpression(_expression_);

        {
            this._moreListArguments_.clear();
            this._moreListArguments_.addAll(_moreListArguments_);
        }

    }
    public Object clone()
    {
        return new AArgList(
            (PExpression) cloneNode(_expression_),
            cloneList(_moreListArguments_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArgList(this);
    }

    public PExpression getExpression()
    {
        return _expression_;
    }

    public void setExpression(PExpression node)
    {
        if(_expression_ != null)
        {
            _expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expression_ = node;
    }

    public LinkedList getMoreListArguments()
    {
        return _moreListArguments_;
    }

    public void setMoreListArguments(List list)
    {
        _moreListArguments_.clear();
        _moreListArguments_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_expression_)
            + toString(_moreListArguments_);
    }

    void removeChild(Node child)
    {
        if(_expression_ == child)
        {
            _expression_ = null;
            return;
        }

        if(_moreListArguments_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        for(ListIterator i = _moreListArguments_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class MoreListArguments_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PMoreListArguments node = (PMoreListArguments) o;

            if((node.parent() != null) &&
                (node.parent() != AArgList.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AArgList.this))
            {
                node.parent(AArgList.this);
            }

            return node;
        }
    }
}
