/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AFunctionCall extends PFunctionCall
{
    private PIdentifier _identifier_;
    private final LinkedList _argList_ = new TypedLinkedList(new ArgList_Cast());

    public AFunctionCall()
    {
    }

    public AFunctionCall(
        PIdentifier _identifier_,
        List _argList_)
    {
        setIdentifier(_identifier_);

        {
            this._argList_.clear();
            this._argList_.addAll(_argList_);
        }

    }
    public Object clone()
    {
        return new AFunctionCall(
            (PIdentifier) cloneNode(_identifier_),
            cloneList(_argList_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFunctionCall(this);
    }

    public PIdentifier getIdentifier()
    {
        return _identifier_;
    }

    public void setIdentifier(PIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }

    public LinkedList getArgList()
    {
        return _argList_;
    }

    public void setArgList(List list)
    {
        _argList_.clear();
        _argList_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_identifier_)
            + toString(_argList_);
    }

    void removeChild(Node child)
    {
        if(_identifier_ == child)
        {
            _identifier_ = null;
            return;
        }

        if(_argList_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_identifier_ == oldChild)
        {
            setIdentifier((PIdentifier) newChild);
            return;
        }

        for(ListIterator i = _argList_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class ArgList_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PArgList node = (PArgList) o;

            if((node.parent() != null) &&
                (node.parent() != AFunctionCall.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AFunctionCall.this))
            {
                node.parent(AFunctionCall.this);
            }

            return node;
        }
    }
}
