/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AIntNumber extends PNumber
{
    private TInteger _integer_;

    public AIntNumber()
    {
    }

    public AIntNumber(
        TInteger _integer_)
    {
        setInteger(_integer_);

    }
    public Object clone()
    {
        return new AIntNumber(
            (TInteger) cloneNode(_integer_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIntNumber(this);
    }

    public TInteger getInteger()
    {
        return _integer_;
    }

    public void setInteger(TInteger node)
    {
        if(_integer_ != null)
        {
            _integer_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _integer_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_integer_);
    }

    void removeChild(Node child)
    {
        if(_integer_ == child)
        {
            _integer_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_integer_ == oldChild)
        {
            setInteger((TInteger) newChild);
            return;
        }

    }
}
