/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AMoreArguments extends PMoreArguments
{
    private PIdentifier _identifier_;
    private final LinkedList _assignValue_ = new TypedLinkedList(new AssignValue_Cast());

    public AMoreArguments()
    {
    }

    public AMoreArguments(
        PIdentifier _identifier_,
        List _assignValue_)
    {
        setIdentifier(_identifier_);

        {
            this._assignValue_.clear();
            this._assignValue_.addAll(_assignValue_);
        }

    }
    public Object clone()
    {
        return new AMoreArguments(
            (PIdentifier) cloneNode(_identifier_),
            cloneList(_assignValue_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMoreArguments(this);
    }

    public PIdentifier getIdentifier()
    {
        return _identifier_;
    }

    public void setIdentifier(PIdentifier node)
    {
        if(_identifier_ != null)
        {
            _identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _identifier_ = node;
    }

    public LinkedList getAssignValue()
    {
        return _assignValue_;
    }

    public void setAssignValue(List list)
    {
        _assignValue_.clear();
        _assignValue_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_identifier_)
            + toString(_assignValue_);
    }

    void removeChild(Node child)
    {
        if(_identifier_ == child)
        {
            _identifier_ = null;
            return;
        }

        if(_assignValue_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_identifier_ == oldChild)
        {
            setIdentifier((PIdentifier) newChild);
            return;
        }

        for(ListIterator i = _assignValue_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class AssignValue_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PAssignValue node = (PAssignValue) o;

            if((node.parent() != null) &&
                (node.parent() != AMoreArguments.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AMoreArguments.this))
            {
                node.parent(AMoreArguments.this);
            }

            return node;
        }
    }
}
