/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ARule4ComparisonOperator extends PComparisonOperator
{
    private TLte _lte_;

    public ARule4ComparisonOperator()
    {
    }

    public ARule4ComparisonOperator(
        TLte _lte_)
    {
        setLte(_lte_);

    }
    public Object clone()
    {
        return new ARule4ComparisonOperator(
            (TLte) cloneNode(_lte_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARule4ComparisonOperator(this);
    }

    public TLte getLte()
    {
        return _lte_;
    }

    public void setLte(TLte node)
    {
        if(_lte_ != null)
        {
            _lte_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lte_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lte_);
    }

    void removeChild(Node child)
    {
        if(_lte_ == child)
        {
            _lte_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lte_ == oldChild)
        {
            setLte((TLte) newChild);
            return;
        }

    }
}
