/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ARule3Expression extends PExpression
{
    private PValue _value_;
    private final LinkedList _moreValues_ = new TypedLinkedList(new MoreValues_Cast());

    public ARule3Expression()
    {
    }

    public ARule3Expression(
        PValue _value_,
        List _moreValues_)
    {
        setValue(_value_);

        {
            this._moreValues_.clear();
            this._moreValues_.addAll(_moreValues_);
        }

    }
    public Object clone()
    {
        return new ARule3Expression(
            (PValue) cloneNode(_value_),
            cloneList(_moreValues_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARule3Expression(this);
    }

    public PValue getValue()
    {
        return _value_;
    }

    public void setValue(PValue node)
    {
        if(_value_ != null)
        {
            _value_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _value_ = node;
    }

    public LinkedList getMoreValues()
    {
        return _moreValues_;
    }

    public void setMoreValues(List list)
    {
        _moreValues_.clear();
        _moreValues_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_value_)
            + toString(_moreValues_);
    }

    void removeChild(Node child)
    {
        if(_value_ == child)
        {
            _value_ = null;
            return;
        }

        if(_moreValues_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_value_ == oldChild)
        {
            setValue((PValue) newChild);
            return;
        }

        for(ListIterator i = _moreValues_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class MoreValues_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PMoreValues node = (PMoreValues) o;

            if((node.parent() != null) &&
                (node.parent() != ARule3Expression.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != ARule3Expression.this))
            {
                node.parent(ARule3Expression.this);
            }

            return node;
        }
    }
}
