/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ARule3ComparisonOperator extends PComparisonOperator
{
    private TGte _gte_;

    public ARule3ComparisonOperator()
    {
    }

    public ARule3ComparisonOperator(
        TGte _gte_)
    {
        setGte(_gte_);

    }
    public Object clone()
    {
        return new ARule3ComparisonOperator(
            (TGte) cloneNode(_gte_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARule3ComparisonOperator(this);
    }

    public TGte getGte()
    {
        return _gte_;
    }

    public void setGte(TGte node)
    {
        if(_gte_ != null)
        {
            _gte_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _gte_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_gte_);
    }

    void removeChild(Node child)
    {
        if(_gte_ == child)
        {
            _gte_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_gte_ == oldChild)
        {
            setGte((TGte) newChild);
            return;
        }

    }
}
