/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ARule11Statement extends PStatement
{
    private final LinkedList _tab_ = new TypedLinkedList(new Tab_Cast());
    private PFunctionCall _functionCall_;

    public ARule11Statement()
    {
    }

    public ARule11Statement(
        List _tab_,
        PFunctionCall _functionCall_)
    {
        {
            this._tab_.clear();
            this._tab_.addAll(_tab_);
        }

        setFunctionCall(_functionCall_);

    }

    public ARule11Statement(
        XTTab _tab_,
        PFunctionCall _functionCall_)
    {
        if(_tab_ != null)
        {
            while(_tab_ instanceof X1TTab)
            {
                this._tab_.addFirst(((X1TTab) _tab_).getTTab());
                _tab_ = ((X1TTab) _tab_).getXTTab();
            }
            this._tab_.addFirst(((X2TTab) _tab_).getTTab());
        }

        setFunctionCall(_functionCall_);

    }
    public Object clone()
    {
        return new ARule11Statement(
            cloneList(_tab_),
            (PFunctionCall) cloneNode(_functionCall_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARule11Statement(this);
    }

    public LinkedList getTab()
    {
        return _tab_;
    }

    public void setTab(List list)
    {
        _tab_.clear();
        _tab_.addAll(list);
    }

    public PFunctionCall getFunctionCall()
    {
        return _functionCall_;
    }

    public void setFunctionCall(PFunctionCall node)
    {
        if(_functionCall_ != null)
        {
            _functionCall_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _functionCall_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_tab_)
            + toString(_functionCall_);
    }

    void removeChild(Node child)
    {
        if(_tab_.remove(child))
        {
            return;
        }

        if(_functionCall_ == child)
        {
            _functionCall_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        for(ListIterator i = _tab_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(_functionCall_ == oldChild)
        {
            setFunctionCall((PFunctionCall) newChild);
            return;
        }

    }

    private class Tab_Cast implements Cast
    {
        public Object cast(Object o)
        {
            TTab node = (TTab) o;

            if((node.parent() != null) &&
                (node.parent() != ARule11Statement.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != ARule11Statement.this))
            {
                node.parent(ARule11Statement.this);
            }

            return node;
        }
    }
}
