/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ARule2ComparisonOperator extends PComparisonOperator
{
    private TLt _lt_;

    public ARule2ComparisonOperator()
    {
    }

    public ARule2ComparisonOperator(
        TLt _lt_)
    {
        setLt(_lt_);

    }
    public Object clone()
    {
        return new ARule2ComparisonOperator(
            (TLt) cloneNode(_lt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARule2ComparisonOperator(this);
    }

    public TLt getLt()
    {
        return _lt_;
    }

    public void setLt(TLt node)
    {
        if(_lt_ != null)
        {
            _lt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lt_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_lt_);
    }

    void removeChild(Node child)
    {
        if(_lt_ == child)
        {
            _lt_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_lt_ == oldChild)
        {
            setLt((TLt) newChild);
            return;
        }

    }
}
