/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ARule8Statement extends PStatement
{
    private final LinkedList _tab_ = new TypedLinkedList(new Tab_Cast());
    private TPrint _print_;
    private PExpression _expression_;
    private final LinkedList _moreExpressions_ = new TypedLinkedList(new MoreExpressions_Cast());

    public ARule8Statement()
    {
    }

    public ARule8Statement(
        List _tab_,
        TPrint _print_,
        PExpression _expression_,
        List _moreExpressions_)
    {
        {
            this._tab_.clear();
            this._tab_.addAll(_tab_);
        }

        setPrint(_print_);

        setExpression(_expression_);

        {
            this._moreExpressions_.clear();
            this._moreExpressions_.addAll(_moreExpressions_);
        }

    }

    public ARule8Statement(
        XTTab _tab_,
        TPrint _print_,
        PExpression _expression_,
        XPMoreExpressions _moreExpressions_)
    {
        if(_tab_ != null)
        {
            while(_tab_ instanceof X1TTab)
            {
                this._tab_.addFirst(((X1TTab) _tab_).getTTab());
                _tab_ = ((X1TTab) _tab_).getXTTab();
            }
            this._tab_.addFirst(((X2TTab) _tab_).getTTab());
        }

        setPrint(_print_);

        setExpression(_expression_);

        if(_moreExpressions_ != null)
        {
            while(_moreExpressions_ instanceof X1PMoreExpressions)
            {
                this._moreExpressions_.addFirst(((X1PMoreExpressions) _moreExpressions_).getPMoreExpressions());
                _moreExpressions_ = ((X1PMoreExpressions) _moreExpressions_).getXPMoreExpressions();
            }
            this._moreExpressions_.addFirst(((X2PMoreExpressions) _moreExpressions_).getPMoreExpressions());
        }

    }
    public Object clone()
    {
        return new ARule8Statement(
            cloneList(_tab_),
            (TPrint) cloneNode(_print_),
            (PExpression) cloneNode(_expression_),
            cloneList(_moreExpressions_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARule8Statement(this);
    }

    public LinkedList getTab()
    {
        return _tab_;
    }

    public void setTab(List list)
    {
        _tab_.clear();
        _tab_.addAll(list);
    }

    public TPrint getPrint()
    {
        return _print_;
    }

    public void setPrint(TPrint node)
    {
        if(_print_ != null)
        {
            _print_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _print_ = node;
    }

    public PExpression getExpression()
    {
        return _expression_;
    }

    public void setExpression(PExpression node)
    {
        if(_expression_ != null)
        {
            _expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expression_ = node;
    }

    public LinkedList getMoreExpressions()
    {
        return _moreExpressions_;
    }

    public void setMoreExpressions(List list)
    {
        _moreExpressions_.clear();
        _moreExpressions_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_tab_)
            + toString(_print_)
            + toString(_expression_)
            + toString(_moreExpressions_);
    }

    void removeChild(Node child)
    {
        if(_tab_.remove(child))
        {
            return;
        }

        if(_print_ == child)
        {
            _print_ = null;
            return;
        }

        if(_expression_ == child)
        {
            _expression_ = null;
            return;
        }

        if(_moreExpressions_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        for(ListIterator i = _tab_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(_print_ == oldChild)
        {
            setPrint((TPrint) newChild);
            return;
        }

        if(_expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        for(ListIterator i = _moreExpressions_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class Tab_Cast implements Cast
    {
        public Object cast(Object o)
        {
            TTab node = (TTab) o;

            if((node.parent() != null) &&
                (node.parent() != ARule8Statement.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != ARule8Statement.this))
            {
                node.parent(ARule8Statement.this);
            }

            return node;
        }
    }

    private class MoreExpressions_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PMoreExpressions node = (PMoreExpressions) o;

            if((node.parent() != null) &&
                (node.parent() != ARule8Statement.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != ARule8Statement.this))
            {
                node.parent(ARule8Statement.this);
            }

            return node;
        }
    }
}
