/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TLeftPar extends Token
{
    public TLeftPar()
    {
        super.setText("(");
    }

    public TLeftPar(int line, int pos)
    {
        super.setText("(");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TLeftPar(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLeftPar(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLeftPar text.");
    }
}
