/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TLte extends Token
{
    public TLte()
    {
        super.setText("<=");
    }

    public TLte(int line, int pos)
    {
        super.setText("<=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TLte(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLte(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLte text.");
    }
}
