/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TPrint extends Token
{
    public TPrint()
    {
        super.setText("print");
    }

    public TPrint(int line, int pos)
    {
        super.setText("print");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TPrint(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPrint(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TPrint text.");
    }
}
