/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TRightPar extends Token
{
    public TRightPar()
    {
        super.setText(")");
    }

    public TRightPar(int line, int pos)
    {
        super.setText(")");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TRightPar(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRightPar(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TRightPar text.");
    }
}
