/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TSquareLeftBr extends Token
{
    public TSquareLeftBr()
    {
        super.setText("[");
    }

    public TSquareLeftBr(int line, int pos)
    {
        super.setText("[");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TSquareLeftBr(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSquareLeftBr(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TSquareLeftBr text.");
    }
}
