/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TSquareRightBr extends Token
{
    public TSquareRightBr()
    {
        super.setText("]");
    }

    public TSquareRightBr(int line, int pos)
    {
        super.setText("]");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TSquareRightBr(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSquareRightBr(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TSquareRightBr text.");
    }
}
