/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class X1PMoreListArguments extends XPMoreListArguments
{
    private XPMoreListArguments _xPMoreListArguments_;
    private PMoreListArguments _pMoreListArguments_;

    public X1PMoreListArguments()
    {
    }

    public X1PMoreListArguments(
        XPMoreListArguments _xPMoreListArguments_,
        PMoreListArguments _pMoreListArguments_)
    {
        setXPMoreListArguments(_xPMoreListArguments_);
        setPMoreListArguments(_pMoreListArguments_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XPMoreListArguments getXPMoreListArguments()
    {
        return _xPMoreListArguments_;
    }

    public void setXPMoreListArguments(XPMoreListArguments node)
    {
        if(_xPMoreListArguments_ != null)
        {
            _xPMoreListArguments_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xPMoreListArguments_ = node;
    }

    public PMoreListArguments getPMoreListArguments()
    {
        return _pMoreListArguments_;
    }

    public void setPMoreListArguments(PMoreListArguments node)
    {
        if(_pMoreListArguments_ != null)
        {
            _pMoreListArguments_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pMoreListArguments_ = node;
    }

    void removeChild(Node child)
    {
        if(_xPMoreListArguments_ == child)
        {
            _xPMoreListArguments_ = null;
        }

        if(_pMoreListArguments_ == child)
        {
            _pMoreListArguments_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xPMoreListArguments_) +
            toString(_pMoreListArguments_);
    }
}
