/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class X1TTab extends XTTab
{
    private XTTab _xTTab_;
    private TTab _tTab_;

    public X1TTab()
    {
    }

    public X1TTab(
        XTTab _xTTab_,
        TTab _tTab_)
    {
        setXTTab(_xTTab_);
        setTTab(_tTab_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XTTab getXTTab()
    {
        return _xTTab_;
    }

    public void setXTTab(XTTab node)
    {
        if(_xTTab_ != null)
        {
            _xTTab_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xTTab_ = node;
    }

    public TTab getTTab()
    {
        return _tTab_;
    }

    public void setTTab(TTab node)
    {
        if(_tTab_ != null)
        {
            _tTab_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tTab_ = node;
    }

    void removeChild(Node child)
    {
        if(_xTTab_ == child)
        {
            _xTTab_ = null;
        }

        if(_tTab_ == child)
        {
            _tTab_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xTTab_) +
            toString(_tTab_);
    }
}
