/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class X2PMoreExpressions extends XPMoreExpressions
{
    private PMoreExpressions _pMoreExpressions_;

    public X2PMoreExpressions()
    {
    }

    public X2PMoreExpressions(
        PMoreExpressions _pMoreExpressions_)
    {
        setPMoreExpressions(_pMoreExpressions_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PMoreExpressions getPMoreExpressions()
    {
        return _pMoreExpressions_;
    }

    public void setPMoreExpressions(PMoreExpressions node)
    {
        if(_pMoreExpressions_ != null)
        {
            _pMoreExpressions_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pMoreExpressions_ = node;
    }

    void removeChild(Node child)
    {
        if(_pMoreExpressions_ == child)
        {
            _pMoreExpressions_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pMoreExpressions_);
    }
}
