/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class X2PMoreArguments extends XPMoreArguments
{
    private PMoreArguments _pMoreArguments_;

    public X2PMoreArguments()
    {
    }

    public X2PMoreArguments(
        PMoreArguments _pMoreArguments_)
    {
        setPMoreArguments(_pMoreArguments_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public PMoreArguments getPMoreArguments()
    {
        return _pMoreArguments_;
    }

    public void setPMoreArguments(PMoreArguments node)
    {
        if(_pMoreArguments_ != null)
        {
            _pMoreArguments_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pMoreArguments_ = node;
    }

    void removeChild(Node child)
    {
        if(_pMoreArguments_ == child)
        {
            _pMoreArguments_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_pMoreArguments_);
    }
}
